package DEMSInterfaceApp;


/**
* DEMSInterfaceApp/DEMSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/khanna/Desktop/Projects/eclipse-workspace/Replica1/src/DEMSInterface.idl
* Thursday, August 1, 2019 5:01:13 o'clock PM EDT
*/

public interface DEMSInterface extends DEMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMSInterface
