package DEMSInterfaceApp;


/**
* DEMSInterfaceApp/DEMSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/khanna/Desktop/Projects/eclipse-workspace/Replica1/src/DEMSInterface.idl
* Thursday, August 1, 2019 5:01:13 o'clock PM EDT
*/

public interface DEMSInterfaceOperations 
{
  String addEvent (String eventID, String eventType, String bookingCapacity);

  // change integer to string in bookcapacity
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface DEMSInterfaceOperations
